apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: currencyservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - currencyservice.hipstershop-prod.demo2.keptn.live.demo.dynatrace.com
  - currencyservice
  http:
  - route:
    - destination:
        host: currencyservice.hipstershop-prod.svc.cluster.local
