apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: adservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - adservice.hipstershop-staging.demo2.keptn.live.demo.dynatrace.com
  - adservice
  http:
  - route:
    - destination:
        host: adservice-canary.hipstershop-staging.svc.cluster.local
    - destination:
        host: adservice-primary.hipstershop-staging.svc.cluster.local
      weight: 100
