apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: cartservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - cartservice.hipstershop-prod.demo2.keptn.live.demo.dynatrace.com
  - cartservice
  http:
  - route:
    - destination:
        host: cartservice.hipstershop-prod.svc.cluster.local
