apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: frontend
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - frontend.hipstershop-staging.demo2.keptn.live.demo.dynatrace.com
  - frontend
  http:
  - route:
    - destination:
        host: frontend-canary.hipstershop-staging.svc.cluster.local
    - destination:
        host: frontend-primary.hipstershop-staging.svc.cluster.local
      weight: 100
