apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: checkoutservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - checkoutservice.hipstershop-staging.demo2.keptn.live.demo.dynatrace.com
  - checkoutservice
  http:
  - route:
    - destination:
        host: checkoutservice.hipstershop-staging.svc.cluster.local
