apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: recommendationservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - recommendationservice.hipstershop-prod.demo2.keptn.live.demo.dynatrace.com
  - recommendationservice
  http:
  - route:
    - destination:
        host: recommendationservice.hipstershop-prod.svc.cluster.local
